# Generated by Django 4.2 on 2026-04-06 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0002_choice_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
