# Generated by Django 4.2 on 2026-03-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses_app', '0001_initial'),
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='courses_app.course'),
        ),
    ]
