# Generated by Django 4.2 on 2026-03-14 23:01

import apps.chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=apps.chat.models.course_pdf_path),
        ),
    ]
