# Generated by Django 4.2 on 2026-03-14 23:12

import apps.chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_initial'),
        ('chat_app', '0006_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.chat.models.ai_document_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.course')),
            ],
            options={
                'verbose_name': 'AI Knowledge Base',
                'verbose_name_plural': 'AI Knowledge Bases',
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
